# -*- coding: utf-8 -*-
"""ModelObj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0DubW-3VLJMtUERFyzyOuA6PuagicNf
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision

from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

num_classes = 9

class NetObj(nn.Module):
    def __init__(self):
        super(NetObj, self).__init__()
        self.model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=False)
        in_features = self.model.roi_heads.box_predictor.cls_score.in_features
        self.model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)